### ISSUE TITLE
第二章代碼無法運行(使用最新版本的code)

### ISSUE THREAD

**Issue by ta0306556** [chenyuntc/pytorch-book#100]
有爬了文，依然是錯在這一行
loss = criterion(output, target)
但是我不知道該如何解決，如果可以，希望麻煩幫忙看一下，謝謝。
环境是pycharm，Python 3.6，pytorch 0.4.1

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-40-2f621ad6225d> in <module>()
      2 target = t.arange(0,10).view(1,10)
      3 criterion = nn.MSELoss()
----> 4 loss = criterion(output, target)
      5 loss # loss是个scalar

D:\Anaconda\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

D:\Anaconda\lib\site-packages\torch\nn\modules\loss.py in forward(self, input, target)
    419 
    420     def forward(self, input, target):
--> 421         return F.mse_loss(input, target, reduction=self.reduction)
    422 
    423 

D:\Anaconda\lib\site-packages\torch\nn\functional.py in mse_loss(input, target, size_average, reduce, reduction)
   1714     else:
   1715         reduction = _Reduction.get_enum(reduction)
-> 1716     return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
   1717 
   1718 

D:\Anaconda\lib\site-packages\torch\nn\functional.py in _pointwise_loss(lambd, lambd_optimized, input, target, reduction)
   1672         return torch.mean(d) if reduction == 'elementwise_mean' else torch.sum(d)
   1673     else:
-> 1674         return lambd_optimized(input, target, reduction)
   1675 
   1676 

RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'target'

**Comment by TJJTJJTJJ** [comment]
target = t.arange(0,10).view(1,10).float() 试一试，只是类型不匹配，你可能之前设置了默认类型没有改回来

**Comment by ta0306556** [comment]
此問題以解決，感謝您的幫忙。
