### ISSUE TITLE
pyinstaller打包pytorch

### ISSUE THREAD

**Issue by xiexupang** [chenyuntc/pytorch-book#105]
one.py 只有三行代码，如下：
import torch
a = torch.zeros(2, 3)
print(a)

当我用pyinstaller把 one.py 打包成exe文件后， 运行exe后，出现如下问题：
failed to execute script one
我怀疑这是pytorch框架的问题，因为我打包其它py文件时并未发生类似问题。
我百度和谷歌了，并没有能解决我问题的相应办法。应该怎样解决这个问题呢？

**Comment by chenyuntc** [comment]
closed due to outdated, feel free to reopen it if you have any problems. Sorry that I was busy in the past half year and did not respond in time.
