### ISSUE TITLE
对于 Chap 6 的一些想法

### ISSUE THREAD

**Issue by xinqiu** [chenyuntc/pytorch-book#11]
首先 文件夹里有两个重复的文件，建议删除一个。

README里的使用方法要是和实战指南中 6.1.8 使用相互一致或者类似更好。实战指南中的使用方式更为可靠。在实际使用中，`--load-model-path=None` 参数不能少，其实要是能够提供训练好的pth那就更好了，没用 GPU 来训练模型真是太痛苦了。

在 `main.py` 的 `train`, `test`, `val` 函数中使用 `tqdm`，这样能看出进度> <，不然有一种死机的感觉。

另外，Chap 5 的 visdom 部分有些和预计结果不同，在 Chap 6 中，loss 图和 val_accuracy 都不能得到曲线，不知道是不是因为版本的原因。

**Comment by chenyuntc** [comment]
visdom 确实有点问题，尤其是最近改版，以及由于部分js文件在国内被墙的原因。
建议试试：
```
pip install --upgrade visdom 
```
然后重启visdom服务
我试验了新版，暂时没发现问题

预训练的模型太大了 :sweat_smile:

**Comment by xinqiu** [comment]
<img width="1251" alt="2018-01-30 12 25 44" src="https://user-images.githubusercontent.com/8972416/35548170-bccf1f66-05b8-11e8-8a53-9d5e884a7b3b.png">
visdom==0.1.7
visdom 日志显示更新，但图并没有更新，请问这是因为墙的缘故么？

**Comment by chenyuntc** [comment]
能贴一下 visdom.server 的log看看吗？

**Comment by xinqiu** [comment]
<img width="406" alt="2018-01-30 2 28 18" src="https://user-images.githubusercontent.com/8972416/35551416-ee0b359a-05c9-11e8-940c-ce2f7c858cdd.png">

**Comment by chenyuntc** [comment]
:sweat_smile:  restart visdom.server and try?

**Comment by xinqiu** [comment]
尝试过多次> <，均无法更新，master和0.3的分支都试过了😂我再来试看看Python3，之前一直用的是Python2

**Comment by chenyuntc** [comment]
我刚clone下来, 在ipython2 下运行
```bash
%run main.py train --data-root=./data/train --use-gpu=True --env=classifier --load-model-path=None --batch-size=4
```
没有问题 :joy: 
![_2018-01-30_14-43-24](https://user-images.githubusercontent.com/9301117/35551787-b737e9da-05cb-11e8-9379-51e555d24b80.png)

**Comment by chenyuntc** [comment]
:blush:
