### ISSUE TITLE
Chapter 7代码无法运行，no_gard() is not callable?

### ISSUE THREAD

**Issue by WhiteSouth** [chenyuntc/pytorch-book#114]
具体的报错是：
File "main.py", line 158, in <module>
    @t.no_grad()
TypeError: 'no_grad' object is not callable

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

我这边是pytorch0.4.0 ，ubuntu下的，求大佬们帮忙看看（T.T）

**Comment by houxiaonan** [comment]
请问有没有解决呀，我也遇到这个问题了。

**Comment by WhiteSouth** [comment]
> 请问有没有解决呀，我也遇到这个问题了。

还没有，我去下载原版的DCGAN的话能跑没有问题，但是具体的修改的话还没调整， 但是这个问题还是不太懂是怎么回事，有什么想法随时交流哈

**Comment by WhiteSouth** [comment]
按照我的理解的话，应该就是就是把那个求取梯度的操作去掉，因为只有训练的时候需要保存，其他过程类似测试之类的，tensor其实不需要gard。所以应该直接注释掉，然后你要测试的时候如果内存不够的话再进行调整就好了吧

**Comment by CF2220160244** [comment]
版本不对的原因
