### ISSUE TITLE
@t.no_grad() #pytorch>0.5

### ISSUE THREAD

**Issue by houxiaonan** [chenyuntc/pytorch-book#117]
Traceback (most recent call last):
  File "D:/Code/code_hxn/pytorch_learning/main.py", line 13, in <module>
    @t.no_grad
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by houxiaonan** [comment]
my torch version is 0.4.0

**Comment by Isnot2bad** [comment]
because 0.4.0 < 0.5

**Comment by chenyuntc** [comment]
You need pytorch>=0.4.1, in which `torch.no_grad` is extended as a wrapper for function.
