### ISSUE TITLE
第三章小试牛刀代码报错

### ISSUE THREAD

**Issue by EdwardSLi** [chenyuntc/pytorch-book#129]
import torch as t

from matplotlib import pyplot as plt
from IPython import display

device = t.device('cpu') #如果你想用gpu，改成t.device('cuda:0')

t.manual_seed(1000)

def get_fake_data(batch_size=8):
    ''' 产生随机数据：y=x*2+3，加上了一些噪声'''
    x = t.rand(batch_size, 1, device=device) * 5
    y = x * 2 + 3 +  t.randn(batch_size, 1, device=device)
    return x, y

w = t.rand(1, 1).to(device)
b = t.zeros(1, 1).to(device)

lr = 0.02  # 学习率

for ii in range(500):
    x, y = get_fake_data(batch_size=4)

    # forward：计算loss
    y_pred = x.mm(w) + b.expand_as(y)  # x@W等价于x.mm(w);for python3 only
    loss = 0.5 * (y_pred - y) ** 2  # 均方误差
    loss = loss.mean()

    # backward：手动计算梯度
    dloss = 1
    dy_pred = dloss * (y_pred - y)

    dw = x.t().mm(dy_pred)
    db = dy_pred.sum()

    # 更新参数
    w.sub_(lr * dw)
    b.sub_(lr * db)

    if ii % 50 == 0:
        # 画图
        display.clear_output(wait=True)
        x = t.arange(0, 6).view(-1, 1)
        y = x.mm(w) + b.expand_as(x)
        plt.plot(x.cpu().numpy(), y.cpu().numpy())  # predicted

        x2, y2 = get_fake_data(batch_size=32)
        plt.scatter(x2.numpy(), y2.numpy())  # true data

        plt.xlim(0, 5)
        plt.ylim(0, 13)
        plt.show()
        plt.pause(0.5)

print('w: ', w.item(), 'b: ', b.item())

Traceback (most recent call last):
  File "D:\Anaconda4.3.1\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-e44b43bd11e0>", line 1, in <module>
    runfile('D:/CMU-mosi/mosei/test1.py', wdir='D:/CMU-mosi/mosei')
  File "D:\PyCharm 2018.3.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/CMU-mosi/mosei/test1.py", line 45, in <module>
    y = x.mm(w) + b.expand_as(x)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'mat2'

**Comment by yuanzhoulvpi2017** [comment]
数据结构问题，一个是float类型一个是long型，你修改一下代码

**Comment by SSYYGAM** [comment]
> 数据结构问题，一个是float类型一个是long型，你修改一下代码
请问怎么修改呢，应该把哪里改成long型

**Comment by SSYYGAM** [comment]
display.clear_output(wait=True)
        x = t.arange(0, 6).view(-1, 1).float()#这里一定要加上.float()
        y = x.mm(w) + b.expand_as(x)
        plt.plot(x.numpy(), y.numpy()) # predicted
这样即可

**Comment by chenyuntc** [comment]
Fixed in new branch

**Comment by FantasyJXF** [comment]
维护不易啊，我目前用PyTorch 1.1.0 也是发现这里不太对

对比调试了好一会
```
x = t.arange(0, 20.0).view(-1, 1)

or

x = t.arange(0, 20, dtype=t.float32).view(-1, 1)
```

**Comment by yuanzhoulvpi2017** [comment]
pytorch里面不同的数据类型是不是不能进行运算？感觉有点奇怪

**Comment by FantasyJXF** [comment]
> pytorch里面不同的数据类型是不是不能进行运算？感觉有点奇怪

```
a = torch.Tensor(2,3)
b = torch.Tensor(2,3).type(torch.int)
c = a + b
```

Out: `RuntimeError: expected backend CPU and dtype Float but got backend CPU and dtype Int`

貌似确实是个需要注意的点

**Comment by Cherry-Wu9** [comment]
可以问一下这个是哪里的作业呀
