### ISSUE TITLE
visdom是否开启正常

### ISSUE THREAD

**Issue by sharmer156** [chenyuntc/pytorch-book#13]
感谢下楼主辛苦付出
visdom替换前

![image](https://user-images.githubusercontent.com/33123492/35761644-e0fa0fa8-08c5-11e8-80de-472c3f4e0aaa.png)

替换index.html后
![image](https://user-images.githubusercontent.com/33123492/35761612-8c13611a-08c5-11e8-9a7f-aed06ed6907f.png)

请问visdom是否正常.

另外
python main.py stylize  --model-path='transformer.pth' \
                 --content-path='amber.jpg'\  
                 --result-path='output2.png'\  
                 --use-gpu=False

是如何执行的，在终端还是编译的，本人新手 ，谢谢

**Comment by chenyuntc** [comment]
不正常    升级visdom看看
  pip install  --upgrade visdom

**Comment by sharmer156** [comment]
![image](https://user-images.githubusercontent.com/33123492/35762837-b1d56858-08d9-11e8-8e84-250fbe102f1c.png)

感谢解答 ，但升级后 替换还是不正常

**Comment by sharmer156** [comment]
![image](https://user-images.githubusercontent.com/33123492/35762843-c1b69bb6-08d9-11e8-9023-2681b6578683.png)

**Comment by chenyuntc** [comment]
我刚刚在我的电脑实验了一下 是可以的,你再试试?

- 卸载
sudo pip3 uninstall visdom
- 重装
sudo pip3 install visdom
- 启动
sudo python3 -m visdom.server

不用替换index.html


请确保 系统中的多个python(python2 python3 anaconda python) 设置正确. 可能你升级的那个并不是你用的那个.

![_2018-02-03_12-16-04](https://user-images.githubusercontent.com/9301117/35762944-0d0daf1c-08dc-11e8-8fc3-2a1094338507.png)

**Comment by chenyuntc** [comment]
对不起.我又重新看了你的issue(早上是在手机看的,没太认真),  你不用替换index.html 就能够使用的了(新版的visdom貌似已经解决了问题)

你的第一张图是没问题的

**Comment by sharmer156** [comment]
感谢热情解答，
是的 我测试其它Visdom的时候没问题（windows ，ubuntu都正常）windows下升级Visdom反而会报错，也替换index.html。
![image](https://user-images.githubusercontent.com/33123492/35763083-12d0b9b4-08df-11e8-96d2-9e80b7d904c6.png)

关键问题可能还是 我是新手 ，没学个编程 ，不明白运行的问题，特别是最后的输出
python main.py stylize --model-path='transformer.pth' 
--content-path='amber.jpg'\
--result-path='output2.png'\
--use-gpu=False

是如何执行的，在终端还是编译的？谢谢

**Comment by chenyuntc** [comment]
在命令行(终端)下运行, 运行结果会保存为output2.png

**Comment by xinqiu** [comment]
@sharmer156 在终端里将命令写在一行然后回车执行就可以了

**Comment by sharmer156** [comment]
非常感谢，训练和测试demo 已成功，非常感谢，而且是在Windows 下噢

![image](https://user-images.githubusercontent.com/33123492/35765282-6c498414-08fb-11e8-98bf-6e9f8a9c0286.png)
![image](https://user-images.githubusercontent.com/33123492/35765293-94e1a0dc-08fb-11e8-8024-98cc6773e6f3.png)
@~ 真的没学个编程也能搞定噢 呵呵 再次感谢
