### ISSUE TITLE
第六章修改类别数

### ISSUE THREAD

**Issue by apple1987** [chenyuntc/pytorch-book#130]
hi 我现在类别数不是2的情况下，该怎么选择模型的时候把num_class参数传递进去呢，一时不知道怎么处理了\(^o^)/~model = getattr(models, ‘SqueezeNet’)() 这里怎么改哦

**Comment by LamboAventador** [comment]
楼主实现多分类了吗，我修改models文件夹下用到的resnet34.py模型中的num_classes，怎么最后还是二分类的预测结果 @apple1987
