### ISSUE TITLE
chapter9 小白windos下运行问题

### ISSUE THREAD

**Issue by sharmer156** [chenyuntc/pytorch-book#14]
![image](https://user-images.githubusercontent.com/33123492/35774481-e34884f6-09ab-11e8-9501-94f3a4997190.png)
Python main.py  运行没问题，但
python main.py gen
python main.py  train就报错
![image](https://user-images.githubusercontent.com/33123492/35774494-33b1ca24-09ac-11e8-92c4-c3bd2998a72e.png)
windos 下的不知道怎么解决？

**Comment by chenyuntc** [comment]
:cry:  我也没用过windows下的环境. PyTorch目前官方尚不支持windows, 不太好说是什么问题

建议装双系统


实在要用,建议参考这篇[文章](https://zhuanlan.zhihu.com/p/26871672) (有一些坑, 你不会Python恐怕很难搞定)

**Comment by cryer** [comment]
我window环境下可以运行，[我的博客](https://cryer.github.io/)，这里有我写的在window上装pytorch教程。我就是这样装的，缺什么在env里pip install 什么就行了

**Comment by chenyuntc** [comment]
如果有任何问题，欢迎重开issue！

**Comment by JohnnyZhang0628** [comment]
你好，请问你解决了吗？我也这是问题。
![image](https://user-images.githubusercontent.com/28375774/63998918-da235f80-cb34-11e9-8fe5-aea2886c1af9.png)
