### ISSUE TITLE
No matching distribution found for torchvison(chapter 7)

### ISSUE THREAD

**Issue by Balzac646729740** [chenyuntc/pytorch-book#16]
安装环境出错：
pip3 install -r requirements.txt

Collecting git+https://github.com/pytorch/tnt.git@master (from -r requiments.txt (line 4))
  Cloning https://github.com/pytorch/tnt.git (to master) to /private/var/folders/pt/7_xdqqdj6l1_xrmp5022g3_r0000gn/T/pip-kt8yy0lq-build
  Requirement already satisfied (use --upgrade to upgrade): torchnet==0.0.1 from git+https://github.com/pytorch/tnt.git@master in /usr/local/lib/python3.6/site-packages (from -r requiments.txt (line 4))
Requirement already satisfied: visdom in /usr/local/lib/python3.6/site-packages (from -r requiments.txt (line 1))
Requirement already satisfied: fire in /usr/local/lib/python3.6/site-packages (from -r requiments.txt (line 2))
Collecting torchvison (from -r requiments.txt (line 3))

error:
  Could not find a version that satisfies the requirement torchvison (from -r requiments.txt (line 3)) (from versions: )
No matching distribution found for torchvison (from -r requiments.txt (line 3))

**Comment by chenyuntc** [comment]
Thanks for your report.
