### ISSUE TITLE
第十章，demo.ipynb

### ISSUE THREAD

**Issue by cryer** [chenyuntc/pytorch-book#17]
有一个可能是个人问题。。。我的resnet50去除FC层输出尺寸竟然是(1,8192)不是(1,2048)，百思不得其解，打印出内容也不是0，是有值的。我换了种写法，结果还是差不多，尺寸变成了(1,2048,2,2)，然后调用(:,:,0,0)的输出和标准答案是一样的，(:,:,0,1),(:,:,1,1),(:,:,1,0)都有所偏差。修改后的代码如下：
```
resnet50 = tv.models.resnet50(pretrained = True).eval()
# del resnet50.fc
modules = list(resnet50.children())[:-1]
resnet50 = t.nn.Sequential(*modules)
# resnet50.fc = lambda x:x
if opt.use_gpu:
    resnet50.cuda() 
    img = img.cuda()
img_feats = resnet50(Variable(img,volatile=True))
img_feats = img_feats[:,:,0,0]
print(img_feats.data.squeeze(0).size())
print(img_feats)
```

**Comment by chenyuntc** [comment]
我猜是你的输入的图片尺寸不对？ 需要是256

**Comment by cryer** [comment]
是3*256*256的，我打印出来看了，而且上面的代码我没改，有resize的。。我也不知道咋回事。。

**Comment by cryer** [comment]
我自己找时间研究研究。

**Comment by chenyuntc** [comment]
https://github.com/pytorch/vision/commit/df7524f2623126af25c6edd43d6e82110d502b69#diff-72833884eef4bf6838c8e9036ff0de6a

问题出在这个更新...  之前pooling的默认stride等于kernel size

临时解决方案:
- 输入图片的尺寸改为 256-> 224
- 或者手动修改 resnet50.avgpool.stride=7

**Comment by cryer** [comment]
我看了一下源代码和resnet论文，原来论文的输入就应该是224*224, 256的话我算了一遍，最后是8*8*2048，然后avgPool一下，步长取1，正好是2*2*2048，没问题了。。如果更新前的话，步长默认7，确实还是1*1*2048，只不过好像就丢弃了一些边缘值。所以我觉得还是改输入尺寸好一些。

谢谢解答，我一开始想当然的就把256当成默认输入尺寸了，就没想过算一遍，反而再三确认输入
是不是256.。。
