### ISSUE TITLE
我将--visdom=False

### ISSUE THREAD

**Issue by GAVANXU** [chenyuntc/pytorch-book#21]

**Comment by GAVANXU** [comment]
我分明设置了--visdom=False，为什么报    sock.connect(sa)ConnectionRefusedError: [Errno 111] Connection refused这种错误呢？

**Comment by chenyuntc** [comment]
应该是 --vis=False  代码中更新了， 抱歉书上的说明没有更新。

**Comment by GAVANXU** [comment]
谢谢
