### ISSUE TITLE
Chapter 7的readme中给出的百度网盘的链接打不开，可以重新发一下吗

### ISSUE THREAD

**Issue by easquelcannotcode** [chenyuntc/pytorch-book#216]
如题

**Comment by wzhings** [comment]
同求。

**Comment by easquelcannotcode** [comment]
> 同求。

我目前这里有，留个邮箱可以发给你。

**Comment by wzhings** [comment]
> 
> 
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

telespam33@gmail.com

Thank you.

**Comment by easquelcannotcode** [comment]
这是anime-faces的数据集：
https://drive.google.com/file/d/1yBPFxLvrLxTWP-MmLH7yUArb7WEXfrqm/view?usp=sharing
Ps: 在读取这个数据集的时程序会报错有几个文件没办法读取，是因为错误提示的那几个是隐藏文件，把它们删除掉就可以了。

**Comment by Sandwiches97** [comment]
嗯嗯收到，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "easquelcannotcode"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 中午11:01
收件人: "chenyuntc/pytorch-book"<pytorch-book@noreply.github.com&gt;; 
抄送: "芝麻开门"<441362952@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [chenyuntc/pytorch-book] Chapter 7的readme中给出的百度网盘的链接打不开，可以重新发一下吗 (#216)





 
这是anime-faces的数据集：
 https://drive.google.com/file/d/1yBPFxLvrLxTWP-MmLH7yUArb7WEXfrqm/view?usp=sharing
 Ps: 在读取这个数据集的时程序会报错有几个文件没办法读取，是因为错误提示的那几个是隐藏文件，把它们删除掉就可以了。

**Comment by zhaokunchu** [comment]
> 
> 
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

十分感谢   1150301643@qq.com

**Comment by AragornKris** [comment]
> 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

同求数据集，十分感谢845803413@qq.com

**Comment by suseyang** [comment]
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

163.ease@163.com
十分感谢

**Comment by Haelles** [comment]
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

haelle@buaa.edu.cn
十分感谢！

**Comment by kangkang189** [comment]
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。
同求，大佬！
1192289125@qq.com

**Comment by Qi-Chuan** [comment]
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。



> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

你好！可以发我一份第七章的数据集吗，十分感谢！ 920892753@qq.com

**Comment by kangkang189** [comment]
我也是在求这个数据集



---原始邮件---
发件人: "Qi-Chuan"<notifications@github.com&gt;
发送时间: 2020年11月4日(周三) 下午4:02
收件人: "chenyuntc/pytorch-book"<pytorch-book@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"kangkang189"<1192289125@qq.com&gt;;
主题: Re: [chenyuntc/pytorch-book] Chapter 7的readme中给出的百度网盘的链接打不开，可以重新发一下吗 (#216)




   
同求。
  
我目前这里有，留个邮箱可以发给你。
    
同求。
  
我目前这里有，留个邮箱可以发给你。
  
你好！可以发我一份第七章的数据集吗，十分感谢！ 920892753@qq.com

**Comment by easquelcannotcode** [comment]
数据集地址https://drive.google.com/file/d/1yBPFxLvrLxTWP-MmLH7yUArb7WEXfrqm/view?usp=sharing
read数据的时候如果报错将其中的隐藏文件删除即可

**Comment by qqyouhappy** [comment]
1506622868@qq.com,谢谢大神

**Comment by MotivatedC** [comment]
大佬，我也同求数据集！！！非常感谢！！！  1836562668@qq.com

**Comment by MotivatedC** [comment]
> > 同求。
> 
> 我目前这里有，留个邮箱可以发给你。

大佬，我也同求数据集！！！非常感谢！！！ 1836562668@qq.com

**Comment by ArlanCooper** [comment]
> > > 同求。
> > 
> > 
> > 我目前这里有，留个邮箱可以发给你。
> 
> [telespam33@gmail.com](mailto:telespam33@gmail.com)
> 
> Thank you.

方便发我一份吗，497464497@qq.com, 谢谢

**Comment by kangkang189** [comment]
https://www.kesci.com/mw/dataset/5d5e06988499bc002c059430/file




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenyuntc/pytorch-book"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 下午3:22
收件人:&nbsp;"chenyuntc/pytorch-book"<pytorch-book@noreply.github.com&gt;;
抄送:&nbsp;"邱震宇"<1192289125@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chenyuntc/pytorch-book] Chapter 7的readme中给出的百度网盘的链接打不开，可以重新发一下吗 (#216)





    
同求。
  
我目前这里有，留个邮箱可以发给你。
  
telespam33@gmail.com
 
Thank you.
  
方便发我一份吗，497464497@qq.com, 谢谢
