### ISSUE TITLE
第十章训练集loss一直上升

### ISSUE THREAD

**Issue by wenshijie110** [chenyuntc/pytorch-book#226]
![image](https://user-images.githubusercontent.com/54231028/97938855-7c844600-1dbd-11eb-850d-9ac2f1d75f86.png)

请问loss为啥是一直增加啊。。。

**Comment by Fangyuanzhi** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenyuntc/pytorch-book"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 上午10:17
收件人:&nbsp;"chenyuntc/pytorch-book"<pytorch-book@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[chenyuntc/pytorch-book] 第十章训练集loss一直上升 (#226)





 

 
请问loss为啥是一直增加啊。。。

不好意思，你发错邮件了吧

**Comment by wenshijie110** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chenyuntc/pytorch-book" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月3日(星期二) 上午10:17 收件人:&nbsp;"chenyuntc/pytorch-book"<pytorch-book@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[chenyuntc/pytorch-book] 第十章训练集loss一直上升 (#226) 请问loss为啥是一直增加啊。。。 不好意思，你发错邮件了吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不好意思啊，可能是发错了，我是新手，操作不怎么熟练，，，
