### ISSUE TITLE
visdom蓝色空页面问题

### ISSUE THREAD

**Issue by laicl** [chenyuntc/pytorch-book#28]
你好，我使用pip install visdom和pip install --upgrade visdom安装visdom之后。
使用python -m visdom.server时，浏览器打开http://localhost:8097页面是蓝色的空页面。
请问，你知道这个问题怎么解决么？谢谢

**Comment by chenyuntc** [comment]
需要更多报错信息？ 最好确认一下 升级的visdom 就是正在用的visdom。

**Comment by laicl** [comment]
谢谢。我更新了linux并且重新安装了visdom。现在可以正常使用了。
