### ISSUE TITLE
诗词生成可以指定格式吗

### ISSUE THREAD

**Issue by 4074** [chenyuntc/pytorch-book#29]
比如五绝、七绝、五律、七律

**Comment by chenyuntc** [comment]
--prefix_words='一二三四五，一二三四五。’ 这样就可以使得后续生成的诗歌遵循五言格式，同时意境也会尽可能的与之相近

比如：
--prefix_words= '细雨鱼儿出,微风燕子斜。' 
--prefix_words='一二三四五，上山打老虎。’

**Comment by 4074** [comment]
是的，但是只有律诗，没有绝句
比如 --prefix_words= '床前明月光‘
会出现错乱

**Comment by chenyuntc** [comment]
嗯嗯，确实是没法控制生成生成句子的长度。 我一般都是自己选取前几句 :joy:

**Comment by cabenn** [comment]
打油诗怎么写？不限制每句长度，自由发挥
