### ISSUE TITLE
第六章代码无法正常运行

### ISSUE THREAD

**Issue by techkang** [chenyuntc/pytorch-book#30]
运行`python main.py train`,报错为‘NameError: name 'opt' is not defined’

**Comment by techkang** [comment]
使用jupyter，输入`%run main.py train`，报错如下：
`user config:
env default
model ResNet34
train_data_root ./data/train/
test_data_root ./data/test1
load_model_path None
batch_size 128
use_gpu False
num_workers 4
print_freq 20
debug_file /tmp/debug
result_file result.csv
max_epoch 10
lr 0.1
lr_decay 0.95
weight_decay 0.0001
parse <bound method parse of <config.DefaultConfig object at 0x000002778FE4F5C0>>
C:\Users\ksc\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
C:\Users\ksc\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py:397: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  "please use transforms.RandomResizedCrop instead.")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\ksc\Desktop\pytorch\chapter6-实战指南\main.py in <module>()
    169 if __name__=='__main__':
    170     import fire
--> 171     fire.Fire()

C:\Users\ksc\Anaconda3\lib\site-packages\fire\core.py in Fire(component, command, name)
    125   context.update(caller_locals)
    126 
--> 127   component_trace = _Fire(component, args, context, name)
    128 
    129   if component_trace.HasError():

C:\Users\ksc\Anaconda3\lib\site-packages\fire\core.py in _Fire(component, args, context, name)
    364 
    365         component, consumed_args, remaining_args, capacity = _CallCallable(
--> 366             component, remaining_args)
    367 
    368         # Update the trace.

C:\Users\ksc\Anaconda3\lib\site-packages\fire\core.py in _CallCallable(fn, args)
    540   (varargs, kwargs), consumed_args, remaining_args, capacity = parse(args)
    541 
--> 542   result = fn(*varargs, **kwargs)
    543   return result, consumed_args, remaining_args, capacity
    544 

C:\Users\ksc\Desktop\pytorch\chapter6-实战指南\main.py in train(**kwargs)
     80         confusion_matrix.reset()
     81 
---> 82         for ii,(data,label) in tqdm(enumerate(train_dataloader)):
     83 
     84             # train model

C:\Users\ksc\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    415 
    416     def __iter__(self):
--> 417         return DataLoaderIter(self)
    418 
    419     def __len__(self):

C:\Users\ksc\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    232             for w in self.workers:
    233                 w.daemon = True  # ensure that the worker exits on process exit
--> 234                 w.start()
    235 
    236             _update_worker_pids(id(self), tuple(w.pid for w in self.workers))

C:\Users\ksc\Anaconda3\lib\multiprocessing\process.py in start(self)
    103                'daemonic processes are not allowed to have children'
    104         _cleanup()
--> 105         self._popen = self._Popen(self)
    106         self._sentinel = self._popen.sentinel
    107         _children.add(self)

C:\Users\ksc\Anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

C:\Users\ksc\Anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

C:\Users\ksc\Anaconda3\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     31 
     32     def __init__(self, process_obj):
---> 33         prep_data = spawn.get_preparation_data(process_obj._name)
     34 
     35         # read end of pipe will be "stolen" by the child process

C:\Users\ksc\Anaconda3\lib\multiprocessing\spawn.py in get_preparation_data(name)
    170     # or through direct execution (or to leave it alone entirely)
    171     main_module = sys.modules['__main__']
--> 172     main_mod_name = getattr(main_module.__spec__, "name", None)
    173     if main_mod_name is not None:
    174         d['init_main_from_name'] = main_mod_name

AttributeError: module '__main__' has no attribute '__spec__'
`

**Comment by techkang** [comment]
又出了别的错。。。跑起来好难啊。。。

**Comment by chenyuntc** [comment]
很抱歉！我做了一些修改， 但没有测试，可能引入了一些新bug。 你可以先试试https://github.com/chenyuntc/pytorch-best-practice   这里的代码，我争取这周末看看

**Comment by techkang** [comment]
今晚我下载了数据集，所有cat和dog的图片已经重命名并放在`/data/train/`文件夹下，运行您的两个版本的代码报错分别如图：
![qq 20180329211620](https://user-images.githubusercontent.com/22956582/38090952-b44ae85a-3396-11e8-8503-ac5fdbebe90f.png)
![qq 20180329211707](https://user-images.githubusercontent.com/22956582/38090953-b4868694-3396-11e8-8c96-306bc5fd3853.png)

**Comment by chenyuntc** [comment]
把 ‘iteritems' 改成 `items`
最好使用python2，当初是用python2 写的

**Comment by chenyuntc** [comment]
第二个报错感觉是你的图片路径有问题  `THumbs`好像是系统生成的缩略图文件

**Comment by techkang** [comment]
嗯，是这样的，问题解决了，实在抱歉打扰了。不过希望再版的时候在书中强调一下数据集的处理。

**Comment by chenyuntc** [comment]
不客气。 
你说的是这个kaggle数据集的处理吗？

**Comment by techkang** [comment]
是的，而且我和同学依然跑不起来第六章代码，我们分析时我们电脑太差了，即使将数据集压缩到一张图片也不行...

**Comment by mageroning** [comment]
@techkang  运行python main.py train,报错为‘NameError: name 'opt' is not defined’
请问这个问题是怎么解决的？

**Comment by grutabow** [comment]
@mageroning  我也遇到了opt未定义的问题。把代码开头的
`# coding:utf8`
改成
`# -*- coding: utf-8 -*-`
就正常了。

**Comment by wuliGGG** [comment]
> @mageroning 我也遇到了opt未定义的问题。把代码开头的
> `# coding:utf8`
> 改成
> `# -*- coding: utf-8 -*-`
> 就正常了。

感谢，我也是这样子

**Comment by MiraculousPower** [comment]
> # -*- coding: utf-8 -*-

感谢

**Comment by MiraculousPower** [comment]
> @mageroning  我也遇到了opt未定义的问题。把代码开头的
> # coding:utf8
> 改成
> # -*- coding: utf-8 -*-
> 就正常了。

感谢
