### ISSUE TITLE
第二章CIFAR-10小练习的编辑器问题

### ISSUE THREAD

**Issue by ccTiming** [chenyuntc/pytorch-book#39]
我的这段代码可以在jupyter notebook上运行, 但是使用pycharm运行失败
dataiter = iter(trainloader)
images, labels = dataiter.next()  # 返回4张图片及标签
print(' '.join('%11s' % classes[labels[j]] for j in range(4)))
show(tv.utils.make_grid((images + 1) / 2)).resize((100, 100))

希望能解答一下, 谢谢!

**Comment by bobo0810** [comment]
Are you sure 两个编程环境是一个吗？

**Comment by ccTiming** [comment]
用的虚拟环境, jupyter在虚拟环境敲得命令, pycharm导入的对应的路径, 我在提交问题之前还特意查看了一下...

**Comment by bobo0810** [comment]
贴上 错误信息看一下？

**Comment by ccTiming** [comment]
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x111607978>>
Traceback (most recent call last):
  File "/Users/chocol/.virtualenvs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 333, in __del__
  File "/Users/chocol/.virtualenvs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 337, in get
AttributeError: Can't get attribute 'FloatTensor' on None

**Comment by ccTiming** [comment]
# 使用torchvision加载并预处理CIFAR-10数据集
# 定义网络
# 定义损失函数和优化器
# 训练网络并更新网络参数
# 测试网络
from __future__ import absolute_import
import torch as t
import torchvision as tv
import torchvision.transforms as transforms
from torchvision.transforms import ToPILImage

show = ToPILImage()  # 可以把Tensor转成Image，方便可视化

# 第一次运行程序torchvision会自动下载CIFAR-10数据集，
# 大约100M，需花费一定的时间，
# 如果已经下载有CIFAR-10，可通过root参数指定

# 定义对数据的预处理
transform = transforms.Compose([
	transforms.ToTensor(),  # 转为tensor
	transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # 归一化
])

# 训练集
trainset = tv.datasets.CIFAR10(
	root='./',
	train=True,
	download=True,
	transform=transform
)
trainloader = t.utils.data.DataLoader(
	trainset,
	batch_size=4,
	shuffle=True,
	num_workers=2
)
# 测试集
testset = tv.datasets.CIFAR10(
	root='./',
	train=True,
	download=True,
	transform=transform
)
testloader = t.utils.data.DataLoader(
	testset,
	batch_size=4,
	shuffle=False,
	num_workers=2
)
classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

# Dataset对象是一个数据集，可以按下标访问，返回形如(data, label)的数据。
data, label = trainset[100]
print(classes[label])
# (data + 1) / 2是为了还原被归一化的数据
show((data + 1) / 2).resize((100, 100))

# Dataloader是一个可迭代的对象，它将dataset返回的每一条数据拼接成一个batch，并提供多线程加速优化和数据打乱等操作。
# 当程序对dataset的所有数据遍历完一遍之后，相应的对Dataloader也完成了一次迭代。
dataiter = iter(trainloader)
images, labels = dataiter.next()  # 返回4张图片及标签
print(' '.join('%11s' % classes[labels[j]] for j in range(4)))
show(tv.utils.make_grid((images + 1) / 2)).resize((100, 100))


这是我的py文件代码, 我上传文件失败了...你可以在pycharm下运行试试, 我的虚拟环境是pip的这个仓库的requirement.txt, 谢谢

**Comment by bobo0810** [comment]
你把floatTensor改为定义Tensor 试试

**Comment by ccTiming** [comment]
transform = transforms.Compose([
	transforms.ToTensor(),  
	transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  
])


这个地方是到Tensor, 其他的地方再没有显示的定义Tensor了

**Comment by bobo0810** [comment]
使用pychram打断点到images, labels = dataiter.next() # 返回4张图片及标签 这一行，然后看看上一行dataiter 里面的内容是什么

**Comment by ccTiming** [comment]
之前打过断点看了的, 是个对象, 有一大串东西,只在dataiter-->sampleiter-->giframe-->f_locals发现f_locals是个字典, 然后返回了四个值, 之前print可以把标签打出来, 但是图片无法展示且报刚刚发的那个错, 说明问题是出现在图片的展示上了...但我实在是找不到原因了....好在这一段不影响后面的运行...总之, 感谢了...

**Comment by chenyuntc** [comment]
show函数其实是将tensor转成PIL.Image，只在notebook中会自动显示图片，在pycharm中不可用。
报错的貌似是dataloader的问题。
