### ISSUE TITLE
Run out of Memory for Chapt. 10 with Feature_extraction

### ISSUE THREAD

**Issue by jizongFox** [chenyuntc/pytorch-book#42]
I am sorry to open this issue because while running the feature_exact.py file from Chapt. 10, I have encountered  the problem of running out of memory. I observed that my RAM increases from 10G to 25 G then an error raised  RuntimeError: Couldn't open shared file mapping: <torch_17120_2057656553>, error code: <1455> at C:\Anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\TH\THAllocator.c:157

I have tried to use gc.collect and delete "imgs" and "features", but the memory use still gets increased.
I am using pytorch 0.3.1 in windows from @peterjc123.

![image](https://user-images.githubusercontent.com/24821325/39343608-cba5b338-49ab-11e8-8184-d32749c6c78d.png)
![image](https://user-images.githubusercontent.com/24821325/39343634-e6038606-49ab-11e8-91be-0954016a5e9c.png)

**Comment by ROCKBOOM** [comment]
@jizongFox Have you solved your problem while update Torch to 0.4.0?

**Comment by jizongFox** [comment]
@ROCKBOOM I fixed the bugs found and made them adapted to pytorch-0.4.0 windows edition. You can see my repo if you want.

**Comment by ROCKBOOM** [comment]
thank you so much！
