### ISSUE TITLE
ch8 p225 图8-5 (a)(b)(c)(d)似乎标的和正文中说的不一样

### ISSUE THREAD

**Issue by arisliang** [chenyuntc/pytorch-book#47]
应该是笔误

**Comment by chenyuntc** [comment]
嗯 发现了 谢谢指正！

应该是：
>其网络结构如图 8-5 所示。图中 (a) 是网络的总体结构，左边 (d) 是一个残差单元的结构图，右边 (b) 和 (c) 分别是下采样和上采样单元的结构图。网络
