### ISSUE TITLE
第二章 计算Loss维数问题

### ISSUE THREAD

**Issue by Diison** [chenyuntc/pytorch-book#52]
第二章 In [31]:

output = net(input)
target = Variable(t.arange(0,10))  
criterion = nn.MSELoss()
loss = criterion(output, target)
loss

loss = criterion(output, target) 报错：
RuntimeError: input and target shapes do not match: input [1 x 10], target [10]

改成loss = criterion(output[0], target)后得到loss是28点多，环境是pycharm，Python 3.6，pytorch 0.4.0

**Comment by TJJTJJTJJ** [comment]
you're right. I maybe know why

**Comment by chenyuntc** [comment]
对，这个bug因为pytorch升级所导致的，已修复 [v0.4分支](https://github.com/chenyuntc/pytorch-book/blob/v0.4/chapter2-快速入门/chapter2: PyTorch快速入门.ipynb)
