### ISSUE TITLE
图像描述在运行作者给的demo时报错

### ISSUE THREAD

**Issue by tyjwan** [chenyuntc/pytorch-book#54]
Traceback (most recent call last):
  File "D:/softWare/Python/pythonrun/Machine-Learning/dataClass/test.py", line 9, in <module>
    data = t.load(opt.caption_data_path)
  File "D:\softWare\Python\pytorch\Anaconda3-5\anaconda\lib\site-packages\torch\serialization.py", line 227, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'caption.pth'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by ROCKBOOM** [comment]
应该把caption.pth放在当前的文件夹下，你可以试一下

**Comment by chenyuntc** [comment]
有问题可以重开issue @tyjwan 
谢谢 @ROCKBOOM
