### ISSUE TITLE
减小计算量的trick

### ISSUE THREAD

**Issue by NickYi1990** [chenyuntc/pytorch-book#64]
1.3.1  定义网络中forward的过程，先用池化再用relu可以大量减少计算量并且得到同样的结果。

before: x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
after: x = F.relu(F.max_pool2d(self.conv1(x)), (2, 2))

**Comment by chenyuntc** [comment]
确实如此，受教了！我会在后续其它网络中考虑。
不过LeNet这个网络不大，我想还和经典实现保持一致。
