### ISSUE TITLE
第三章71页关于numpy数组与torch张量共享内存的问题

### ISSUE THREAD

**Issue by 08zhangyi** [chenyuntc/pytorch-book#66]
3.1.2节，书上通过例子讲述numpy对象和tensor对象的内存共享问题。根据我的实验，发现书上写的有一些错误：
b = t.from_numpy(a)，采用这种方式从numpy对象构造tensor对象，是可以实现内存共享的
但是
b = t.Tensor(a)，采用这种方式从numpy对象构造tensor对象，**不能够**实现内存共享
我的pytorch版本为0.4.0，windows10，python3.6

**Comment by Diamondfan** [comment]
书中论述没有错误，请仔细阅读。

**Comment by 08zhangyi** [comment]
3.2.2节，88页和89页的代码内容，在调用y.grad_fn.saved_variables，报错
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-3ba15276330c> in <module>()
----> 1 y.grad_fn.saved_variables

AttributeError: 'MulBackward1' object has no attribute 'saved_variables'
我在搜索pytorch的官方0.4.0的文档的时候，也没有搜索到saved_variables的内容，因此我怀疑在0.4.0中，此功能已经取消。我的环境和上个问题一致

**Comment by chenyuntc** [comment]
对，saved_variables已删除，会在下一个版本更新。
