### ISSUE TITLE
chapter 7 代码报错

### ISSUE THREAD

**Issue by yinggo** [chenyuntc/pytorch-book#67]
训练python main.py train --nogpu --vis=False
`File "main.py", line 152, in train
    tv.utils.save_image(fix_fake_imgs.data[:64], '%s/%s.png' % (opt.save_path, epoch), normalize=True,
UnboundLocalError: local variable 'fix_fake_imgs' referenced before assignment
`
没有改动过原代码，，，，求解，，，

**Comment by tianke0711** [comment]
我同样错误，你可解决，可留下联系方式一起探讨学习。

**Comment by chenyuntc** [comment]
是个bug，如果你指定--vis=False 的话就不会执行这句话

>                 fix_fake_imgs = netg(fix_noises)

把这句话拷贝到152行即可。我会在下一个版本修复它。

**Comment by tianke0711** [comment]
@chenyuntc  谢谢啦。 大佬如果能更新github信息快点就最好了。还有就是希望大佬能够快点回复我们。
