### ISSUE TITLE
在readme中添加引用

### ISSUE THREAD

**Issue by techkang** [chenyuntc/pytorch-book#69]
希望能在readme.md中添加引用格式，方便其他人写报告或论文时引用您的工作，例如：
`
@inproceedings{pytorchbook,  
Author = {Chen Yun},  
Title = {PyTorch tutorials and fun projects including neural talk, neural style, poem writing, anime generation},  
Year = {2018},  
booktitle = {https://github.com/chenyuntc/pytorch-book},  
}
`

**Comment by chenyuntc** [comment]
十分荣幸，暂时可以使用
```
@book{yun2018pytorchtutorials,
  title={PyTorch: Introduction and Practice},
  author={Yun Chen},
  volume={1},
  year={2018},
  publisher={Publishing House of Electronics Industry}
}
```
