### ISSUE TITLE
Chap Autograd 中无法查看saved_variables

### ISSUE THREAD

**Issue by xinqiu** [chenyuntc/pytorch-book#7]
正在阅读您的Pytorch-book 这个教程，在进行 Chap 3 Autograd 时，遇到了一个在 Google 和 Github issues 中没出现的问题，想询问您一下。在第 25 行，执行 y.grad_fn.saved_variables 时，显示如下错误

```
-----------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-3ba15276330c> in <module>()
----> 1 y.grad_fn.saved_variables

AttributeError: 'MulBackward1' object has no attribute 'saved_variables'
```

没有能够显示应该显示的结果

```
(Variable containing:
  0.3356
 [torch.FloatTensor of size 1], Variable containing:
  1
 [torch.FloatTensor of size 1])
```

之后也是，也就是说，我无法得到 saved_variables 这个变量的值

torch==0.3.0.post4
python 2.7.10(14)/3.5.2 均无法成功运行
Ubuntu / Mac OS X 10.12.6 均尝试无果

**Comment by chenyuntc** [comment]
可能是版本问题，我等下看看。

**Comment by chenyuntc** [comment]
确实是版本问题，PyTorch0.3 中把许多python的操作转移到了C++中，saved_variables 现在是一个c++的对象，无法通过python访问。
近期我会抽空将代码迁移到[v0.3](https://github.com/chenyuntc/pytorch-book/blob/0.3/chapter3-Tensor和autograd/Autograd.ipynb) 中。

谢谢你的反馈！！!
