### ISSUE TITLE
第三章，volatile=True 的用法已不再有效。另外 Variable API 已被弃用。

### ISSUE THREAD

**Issue by GaoYang-Thu** [chenyuntc/pytorch-book#70]
我的pytorch版本=0.4.0
1，volatile 方法失效。官方文档建议使用.no_grad，例子如下：
```python 
x = torch.tensor([1], requires_grad=True)
with torch.no_grad():   
...   y = x * 2  
y.requires_grad  
False
```
2，Variable API已被弃用。使用 `Variable(tensor)`得到的不是Variable而是tensor。
创建tensor时注明requires_grad=True，得到的tensor可以直接反向传播。
```python
x = torch.randn((1), requires_grad=True)
w = torch.randn((1),requires_grad=True)
y = x * w
y.backward()
```
参考官方文档请见[这里](https://pytorch.org/docs/stable/autograd.html?highlight=grad#torch.autograd.no_grad)  

希望能在教程里作出相应说明。
感谢作者！

**Comment by ujsyehao** [comment]
@GaoYang-Thu 是的，variable API被弃用

**Comment by chenyuntc** [comment]
我会在下一版本更新

**Comment by GaoYang-Thu** [comment]
感谢作者！

**Comment by GaoYang-Thu** [comment]
感谢！@chenyuntc
