### ISSUE TITLE
第四章代码用法有些疑惑（关于@修饰符）

### ISSUE THREAD

**Issue by 08zhangyi** [chenyuntc/pytorch-book#73]
4.6节 nn.Module深入分析中第124页的第一段代码（本页第三行）
x = self.param1@input
这个里面的@是什么用法呢？百度上都是讲述为函数修饰符的，不符合这里的情形，没有查到合适的解释，特来请教。

**Comment by chenyuntc** [comment]
对。 不过只在python 3中支持
