### ISSUE TITLE
chapter10-图像描述(Image Caption)  运行demo.ipynb出错

### ISSUE THREAD

**Issue by zhangqianjin** [chenyuntc/pytorch-book#74]
python3.5 + pytorch 0.4

results = model.generate(img_feats.data[0])
print('\r\n'.join(results))

KeyError                                  Traceback (most recent call last)
<ipython-input-26-7eb52668358c> in <module>()
      5 #      model.cuda()
      6 
----> 7 results = model.generate(img_feats.data[0])
      8 # print('\r\n'.join(results))

*/PyTorch-book/chapter10-图像描述(Image Caption)/model.py in generate(self, img, eos_token, beam_size, max_caption_length, length_normalization_factor)
     58         sentences, score = cap_gen.beam_search(img)
     59         sentences = [' '.join([self.ix2word[idx] for idx in sent])
---> 60                      for sent in sentences]
     61         return sentences
     62 

*/PyTorch-book/chapter10-图像描述(Image Caption)/model.py in <listcomp>(.0)
     58         sentences, score = cap_gen.beam_search(img)
     59         sentences = [' '.join([self.ix2word[idx] for idx in sent])
---> 60                      for sent in sentences]
     61         return sentences
     62 

*/PyTorch-book/chapter10-图像描述(Image Caption)/model.py in <listcomp>(.0)
     57         img = self.fc(img).unsqueeze(0)
     58         sentences, score = cap_gen.beam_search(img)
---> 59         sentences = [' '.join([self.ix2word[idx] for idx in sent])
     60                      for sent in sentences]
     61         return sentences

KeyError: tensor(4)

**Comment by zhangqianjin** [comment]
这个问题是idx是tensor类型的，需要把它变成整形的，所以需要加int，即为int(idx)，这样就可以正常出结果了

**Comment by chenyuntc** [comment]
我会在下一个版本更新代码以支持0.4

**Comment by wangdepeng1** [comment]
我想请问下，训练好的模型，给不同的图片生成的句子都是一样的，是什么原因呢？
