### ISSUE TITLE
How to set Multi-GPU with the method you provide in chapter 6?

### ISSUE THREAD

**Issue by Yedis** [chenyuntc/pytorch-book#77]
Hello!
What you said on Chapter 6 is pretty good! 
I have a problem that I don't know how to do multi-GPU task.
I try to use  `nn.DataParallel`,  but then when i use `model.load`
I get `AttributeError: 'DataParallel' object has no attribute 'load'` and I don't know how to fix it

**Comment by Captainzj** [comment]
> Hello!
> What you said on Chapter 6 is pretty good!
> I have a problem that I don't know how to do multi-GPU task.
> I try to use `nn.DataParallel`, but then when i use `model.load`
> I get `AttributeError: 'DataParallel' object has no attribute 'load'` and I don't know how to fix it

Hello!
How to solve the problem?

**Comment by Canadalynx** [comment]
Are you sure that it's "model.load",not "model.load()".
