### ISSUE TITLE
从第二章开始运行代码时，就会经常出现数据类型不匹配的问题

### ISSUE THREAD

**Issue by ykeivn** [chenyuntc/pytorch-book#81]

**Comment by ykeivn** [comment]
RuntimeError: Expected object of type torch.LongTensor but found type torch.FloatTensor for argument #2 'mat2'
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #4 'src'

**Comment by andrewcywang** [comment]
我按照您的書執行到損失函數的時候，
损失函数
nn实现了神经网络中大多数的损失函数，例如nn.MSELoss用来计算均方误差，nn.CrossEntropyLoss用来计算交叉熵损失。

output = net(input)
target = Variable(t.arange(0,10))  
criterion = nn.MSELoss()
loss = criterion(output, target)
loss

執行之後會出下面的錯誤:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-44-c886cf227c32> in <module>()
      2 target = Variable(t.arange(0,10))
      3 criterion = nn.MSELoss()
----> 4 loss = criterion(output, target)
      5 loss

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\loss.py in forward(self, input, target)
    419 
    420     def forward(self, input, target):
--> 421         return F.mse_loss(input, target, reduction=self.reduction)
    422 
    423 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py in mse_loss(input, target, size_average, reduce, reduction)
   1714     else:
   1715         reduction = _Reduction.get_enum(reduction)
-> 1716     return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
   1717 
   1718 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py in _pointwise_loss(lambd, lambd_optimized, input, target, reduction)
   1672         return torch.mean(d) if reduction == 'elementwise_mean' else torch.sum(d)
   1673     else:
-> 1674         return lambd_optimized(input, target, reduction)
   1675 
   1676 

RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'target'

請問程式要如何改呢?

**Comment by chenyuntc** [comment]
请试试新版代码，如果有问题欢迎重开这个issue
