### ISSUE TITLE
chapter2: RuntimeError Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'target'

### ISSUE THREAD

**Issue by simonwangwxm** [chenyuntc/pytorch-book#82]
```output = net(input)
target = Variable(t.arange(0, 10))
criterion = nn.MSELoss()
loss = criterion(output, target)
loss
```
ubuntu 16.04, python 3.6.3, pytorch 0.4.1, RuntimeError occurs that 
`RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'target'`

The error is at `target = Variable(t.arange(0, 10))`, which return a Tensor with `target.type() == 'torch.LongTensor'`, while mismatched with `output.type() == 'torch.FloatTensor'`. 

Therefore, I modify it to 
`target = Variable(t.arange(0, 10).float())`

But another error about shape mismatched occurs
`RuntimeError: input and target shapes do not match: input [1 x 10], target [10] at /pytorch/aten/src/THNN/generic/MSECriterion.c:12`

so add `.view()`, 
`target = Variable(t.arange(0, 10).float()).view(1, -1)`

Done. 

Hope the author can modify the error. Thx~

**Comment by kongzewuxin** [comment]
Thanks for your answer!!!
