### ISSUE TITLE
第五章visdom

### ISSUE THREAD

**Issue by jilner** [chenyuntc/pytorch-book#84]
运行p154最上面程序，一直报错
'>' not supported between instances of 'float' and 'NoneType'
Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.

**Comment by chenyuntc** [comment]
嗯嗯要这样才对：
```
 visdom.Visdom(env=env,use_incoming_socket=False
```
这是新版visdom的一个上游依赖的问题
