### ISSUE TITLE
new()

### ISSUE THREAD

**Issue by TJJTJJTJJ** [chenyuntc/pytorch-book#97]
我在看第九章代码的时候，发现作者一直使用tensor.data.new()方法来重建相同类型的tensor，在0.4中variable取消，变成了tensor，我试了试tensor.new()和tensor.data.new()，发现两者新建的tensor都没有grad_fn，计算图都取消了，不知道这两种新建的方法有什么很大的区别吗？烦请作者解答。另外，我在官网上看到的是new_tensor()方法，不知道这个和作者使用的new()区别在哪？如果有懂的朋友，也请指点一二。

**Comment by chenyuntc** [comment]
抱歉这么久才回复： tensor.new 和tensor.data.new 本质上都是 torch.Tensor(dtype=tensor.dtype,device=tensor.device), 只是为了写起来方便
